### ISSUE TITLE
Ribs need to be removed

### ISSUE THREAD

**Issue by Mythos** [Mythos/RimWorld-Extended-Human-Body-Simulation#3]
This mod adds separate ribs, which have been replaced by a single ribcage.

EPOE still has the definitions for separate ribs, so the mod doesn't break here, but it isn't using the separate ribs anymore.
Also this is causing issues when running with RBSE

**Comment by Mythos** [comment]
I guess the ModuleSlots are used for Crafted Mutants... But I don't think
it makes sense to have one for the ribcage as there wouldn't be a benefit
of having a second ribcage that I could think of.

EPSIL0N <notifications@github.com> schrieb am Fr., 9. Nov. 2018, 09:27:

**Comment by E-Gamma-102** [comment]
Removing the individual ribs makes it unable to be assigned in EDBPrepareCarefully before games starts when you could before. I know this will be v. low on the priority list just wanted you guys know.

**Comment by EPSIL0N** [comment]
I am pretty sure that is an EPOE issue as only the legacy EPOE still has ribs the last time I checked, if EPOE is ever remade to have the ribs again in a main version then a compatibility patch/version of EHBS and CM could be needed.
